---
title: "Tidy Coral"
author: "Elisa Bayraktarov"
date: "19 June 2019"
output: html_document
---

```{r setup, warning = FALSE, message=FALSE}
#install libraries
library(tidyverse) # install.packages("tidyverse")
library(janitor) # install.packages("janitor")
library(skimr) # install.packages("skimr")
library(stringr) # install.packages("stringr")

## data filepaths/urls ----

# These links can be found at:
#   http://ohi-science.org/uq-training/ --> Tidy Coral

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'

```

# Read in benthic data

```{r benthic raw}
benthic_raw <- read_csv(benthic_url)

head(benthic_raw)
dim(benthic_raw)

```

# Wrangle

```{r wrangle!}

# wrangle time

benthic <- benthic_raw %>% 
  janitor::clean_names() # this function does code-complient names

# explore the dataset
head(benthic)
names(benthic)

# select our columns for the analysis
# we want to overwrite the variable benthic
benthic <- benthic %>% 
  select(id_name, point, x, y , id_date) %>% 
  mutate(date = stringr::str_remove_all(id_date, "#"))

benthic

```

# Explore

```{r explore the data}

summary(benthic)

skimr::skim(benthic)

unique(benthic$date)
unique(benthic$id_name)

ggplot(benthic, aes(date, fill = id_name))+
  geom_bar()

```

# Buoy Data

```{r}

# import buoy data

# This doesn't work because it's not comma separated - it's a txt file
buoy <- read_csv(buoy_url)
head(buoy)

# Try reading in the txt data again with read_table2
buoy_raw <- read_table2(buoy_url)
head(buoy_raw)

```

# Wrangle!
```{r}
buoy <- buoy_raw

# 1. overwrite column names
names(buoy) <- str_c(
  names(buoy),
  buoy %>% filter(`#YY` == "#yr"), # variable name with `#`
  sep = "_")

# Looks a lot better but not quite right
names(buoy)

# 2. clean up the slashes, get rif of `#` and `/`

names(buoy) <- str_replace_all(names(buoy), "#", "")
names(buoy) <- str_replace_all(names(buoy), "/", "")

head(buoy)

# 3. remove redundant second row
buoy <- buoy %>%
  filter(`YY_yr` != "#yr")
```


# Explore

```{r}

ggplot(buoy, aes(WTMP_degC))+
  geom_bar()

```

# Join

```{r}

head(benthic)
head(buoy)

# unite buoy dates and create a new date column in buoy
buoy <- buoy %>%
  tidyr::unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

head(buoy)
buoy$date

# left-join benthic by date
bb_join <- benthic %>%
  left_join(buoy, by = "date")

## let's select a few columns and inspect:
bb_join %>%
  select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>%
  head()

```

